# Generated by Django 3.1.3 on 2021-11-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_auto_20211108_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_online',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
