# Generated by Django 3.1.3 on 2021-11-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_auto_20211108_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='file',
        ),
    ]
